name: The Long View
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#8bc5e7'
    - '#6e5a92'
    - '#968fac'
    - '#4087be'
  brandStrength: 0.2992572
  lightness: 0.07461443
  saturation: 0.5797053
  rhythmicContrast: 0.3346959
purpose: []
